sudo: required

language: bash

services:
  - docker

branches:
  only:
  - master

before_install:
  - git clone https://github.com/yang-l/docker-in-travis-ci.git
  - docker build -t x86_64 -f Dockerfile.dev.x86_64.ubuntu.xenial ./docker-in-travis-ci

install:
  - docker build -t consul-builder -f Dockerfile.build.consul.x86_64 .

script:
  - docker run -i --rm consul-builder bash -c "/srv/work/src/github.com/hashicorp/consul/bin/consul --version"
